# This workflow will install Python dependencies, run tests and lint with a variety of Python versions using Poetry

name: poetry-test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      # Cache the installation of Poetry itself. This prevents the workflow
      # from installing Poetry every time, which can be slow
      - name: Cache poetry install
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-1.8.2-0
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
        
      - name: Install project dependencies
        run: poetry install --no-interaction
        
      - name: Run tests
        run: poetry run pytest -v
